language: objective-c
cache:
  directories:
    - vendor/bundle
    - example/Pods
    - project/Pods
install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - bundle exec pod instlal --project-directory=example/
  - bundle exec pod instlal --project-directory=project/
script:
  - bundle exec rake test:ios
  - bundle exec rake build:ios
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8