language: objective-c
osx_image: xcode61
rvm: 2.1.0
notifications:
  email: false
podfile: path/to/Podfile
before_install:
  - brew update
  - brew install xctool
  - cd project
script:
  - xctool test -workspace project.xcworkspace -scheme project -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  #- xcodebuild -project project.xcodeproj -scheme project test -sdk iphonesimulator8.1 | xcpretty -c; exit ${PIPESTATUS[0]}
