language: objective-c
notifications:
  email: false
osx_image: xcode7.3
before_install:
  - brew bundle
  - bundle install
xcode_sdk: iphonesimulator
install: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - secure: 2/0f7XbolENmzm4lQGHzIfEKHEg9unoWFI3bf4X4BiW7w89T4e/oflNaDNRd/0sqiIvwl24opnWP4MDL67xMFGc6olc2w/ME+EucPFH/alIUEUl9eIESm6RMbj0a8nNkgAcSoTumu1wMnxuiel6ZPIzTfKYaWqhaR4Xu0OwQNJ5na6E/9Z+38lxOEct6jacJrkqEiKieg1i3h25GMvQPem1lJ8y3R/3O/T4OI+6jVFtol8Ri9+OiqcuJbfPi83PtVhbWxSlTvqAAYOOsOkVpAORhyE0zRv8ro6piaG8DvZb3jkJ3PKklrv5Nu4L047ZixSbauoVMJ/9nyxsXZseGNFRYgl2z0HeE2hbaoko8LRMtd/g745L0/fi3FkoEvPeiJmEczLcvqUpk67ZeqI95KlxsiwtySXRMXd+jPi6BF8zojSMh3YFQjwlXmbN2hQ69hGNaP1qGTkYX/awEnmRR6uqS5tiJBuEHMScEhjScMQcnO9u4SsLD+wgCjr+oXu+YQSl4IaAkhOjzqqJTVYYXVampHUQY+euZzA88rM0fRKHY1s5CdmBJyAuoys2j3zuVed3tyC9NCnJVzzAPbxUD1vMUwNTNg99cvqY+bDLDSvqIBL4DGM3z09ES0trlihDeCLd0a8k+24Brd5r8SLRkWuRmnEARChT6oOTnxzPKNCY=
  - secure: GDfGPDE6Q8ryNCDG+2XLgrzlrB0pvT5RinZuHdtR/DKFRdyt7LhJnjTFuH/v5HG6Ule6hwuFV0ca7dRNNLb9udql2U/gqSOLphobZyJlMCzLE0G4XUeCNag6ymA8gHwEeXWjbQqY6nOnx+XZj/ZiiOdKCkKQrVsdBsfvniF7yKUX9dZnuZyaj5842WTXJ7XxmbxDrQMOl6JL1oegbF4M0PWYmgSZSre1Q5IAHgeY/ERHBp75MyKrJj6rBmmKka0U5OaFhFzXV8EtqSHSiWfXEEl6OfBzuLoHPrpZOzgV32DKDeqOlw4ikUkBAYl6FToMm3Q1wQKFL+AoutkHcB83U37h/D7Po2VEIy7SygBMm7bvCQZTnH/x89ZC4pMlvvlB97SucW+9YW7NCO1+8j6tcmS91Q3I2dRRjk3B8ZRg2sT6+LogjPqvRDaV7PcybGWHP0+JdtpZmHg56S/xT5a4zHCd3l8lVAh9ubc08YPLU4jUMfNaBEnfNZFQv8QUMX03283/cZYUVSj3fUkApR2tinhWVjGnWPj3AUn1nSCiAgIQ2zcFtA8H7bRQrJwpxxIGdw1S5L7xu4tdM6mNUJg2lhOw3EI2vDZ9QNsKyO2Xj5+0jmx47jTtpKHRG0SzE/UJFpK9vR6olZoMSfqp7a7kUUV876eWiUIj9si9ykGOa8Q=
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - bundle exec fastlane tests
  - bundle exec fastlane build
before_script:
  - bundle exec fastlane setup
